DEFAULT_THRESHOLD = 0.5
DEFAULT_LEARNING_RATE = 0.005
DEFAULT_LABEL_TYPE = 'gender'
#DEFAULT_LABEL_TYPE = 'gender'
DEFAULT_INIT = 'imagenet'
DEFAULT_IMG_SIZE = 587
DEFAULT_KERNEL = 'median'
DEFAULT_KERNEL_SIZE = 23 
DEFAULT_DNN_TYPE = 'inceptionv3'
DEFAULT_INIT = 'imagenet'
DEFAULT_NUM_CHANNELS=3
CHANNEL_FIRST=False
SUBTRACT_BG=True
MASK=True

TRAIN_RATIO=0.75
VAL_RATIO=0.10
FC_EPOCHS = 10
EPOCHS = FC_EPOCHS + 90
BATCH_SIZE = 16
REG_CONSTANT = 1e-03
NUM_CLASSES = 2
NUM_WORKERS = 12
MAX_QUEUE_SIZE = NUM_WORKERS * 8 

DEFAULT_LAYER='concatenate_3'
